return {
  "nvim-treesitter/nvim-treesitter",
  dependencies = { "windwp/nvim-ts-autotag", "JoosepAlviste/nvim-ts-context-commentstring" },
  build = ":TSUpdate",
  config = function()
    require("nvim-treesitter.configs").setup({
      ensure_installed = {
        "css",
        "dockerfile",
        "fish",
        "git_rebase",
        "gitattributes",
        "gitignore",
        "glsl",
        "go",
        "graphql",
        "html",
        "http",
        "javascript",
        "json",
        "lua",
        "php",
        "python",
        "rust",
        "scss",
        "sql",
        "tsx",
        "typescript",
        "yaml",
      },
      highlight = { enable = true },
      incremental_selection = { enable = true },
      indent = { enable = true },
      autotag = { enable = true },
      context_commentstring = { enable = true, enable_autocmd = false },
    })
  end,
}
