FROM registry.fedoraproject.org/fedora-toolbox:41

LABEL name="alexanderflink/dev-toolbox" \
    summary="Development toolbox" \
    maintainer="Alexander Flink"

# Install dnf packages
RUN dnf -y copr enable atim/lazygit \
    && dnf -y update \
    && dnf -y install \
    bat \
    cargo \
    cmake \
    fish \
    fzf \
    httpie \
    jq \
    lazygit \
    nodejs22 \
    python3 \
    ripgrep \
    ruby \
    rust \
    timew \
    tldr \
    pnpm \
    zoxide \
    glances \
    && dnf clean all

# Install rust packages
ENV CARGO_HOME=/usr/local/.cargo
RUN cargo install --locked starship yazi-fm yazi-cli
ENV PATH=$PATH:$CARGO_HOME/bin

# Install npm packages
ENV PNPM_HOME=/usr/local/share/pnpm
RUN mkdir -p /usr/local/share/pnpm

RUN pnpm install -g \
    vercel

# Set up environment
COPY ./env.fish /etc/env.fish
ENV HOSTNAME=dev-toolbox
ENV EDITOR=vi
ENV SHELL=/usr/bin/fish
